In [ ]:
1 A database is an organized collection of data stored in a computer system and usually controlled by a database management system (DBMS). The data in common databases is modeled in tables, making querying and processing efficient. Structured query language (SQL)
is commonly used for data querying and writing

SQL databases are relational, while NoSQL databases are non-relational.
SQL databases use structured query language (SQL) and have a predefined schema, while NoSQL databases have dynamic schemas for unstructured data.
SQL databases are table-based, while NoSQL databases can be document-based, key-value pairs, and graph databases.
SQL databases are vertically scalable, while NoSQL databases are horizontally scalable.
SQL databases suit multi-row transactions, while NoSQL is better for unstructured data like documents or JSON.

In [ ]:
2 DDLor Data Definition Language actually consists of the SQL commands that can be used to define the database schema.
It simply deals with descriptions of the database schema and is used to create and modify the structure of database objects in the database. 

The CREATE TABLE command creates a new table in the database.
The ALTER TABLE command adds, deletes, or modifies columns in a table.
The ALTER TABLE command also adds and deletes various constraints in a table.
The DROP TABLE command deletes a table in the database.
The TRUNCATE TABLE command deletes the data inside a table, but not the table itself.

In [ ]:
3 DML is short name of Data Manipulation Language which deals with data manipulation, and includes most common SQL statements such SELECT, INSERT, UPDATE, DELETE etc, 

In SQL, INSERT, UPDATE, and DELETE are Data Manipulation Language (DML) statements that allow users to view and manage data 1. Here are some examples of how these statements work:

INSERT: This statement is used to add new data to a table. For example, let’s say we have a table called students with columns id, name, age, and gender. We can add a new student to the table using the following SQL statement:

UPDATE: This statement is used to modify existing data in a table. For example, let’s say we want to update John Doe’s age to 21.

DELETE: This statement is used to remove data from a table. For example, let’s say we want to delete the row where the id column is 1.

In [ ]:
4 We can define DQL as follows it is a component of SQL statement that allows getting data from the database and imposing order upon it. It includes the SELECT statement. This command allows getting the data out of the database to perform operations with it.

Any SQL query is not fundamentally related to performance, but when used in large fields and its amount is expected to be very large, the performance issue is always present. To resolve these issues, 
the only possible solution is that the query must determine what it is doing and how much time it is consuming to do that task. And when any data analysts know about it, they may be able to optimize that query a lot.

In [ ]:
5 A primary key is used to ensure that data in the specific column is unique. A column cannot have NULL values. It is either an existing table column or a column that is specifically generated by the database according to a defined sequence. 
Example: STUD_NO, as well as STUD_PHONE both, are candidate keys for relation STUDENT but STUD_NO can be chosen as the primary key (only one out of many candidate keys). 

A foreign key is a column or group of columns in a relational database table that provides a link between data in two tables. It is a column (or columns) that references a column (most often the primary key) of another table. 
Example: STUD_NO in STUDENT_COURSE is a foreign key to STUD_NO in STUDENT relation.

In [ ]:
import mysql.connector
mydb = mysql.connector.connect(
  host="localhost",
  user="abc",
  password="password"
)
mycursor = mydb.cursor()
#mycursor.execute("select * from test2.test_table")
mycursor.execute("select c1 , c5 from test2.test_table")
for i in mycursor.fetchall() :
    print(i)

mydb.close()

In [ ]:
DML
JOIN
WHERE
GROUP
HAVING
SELECT
DISTICT
ORDER BY
LIMIT